services:
  - type: web
    name: video-downloader
    env: python
    plan: standard
    buildCommand: ""
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
