services:
  - type: web
    name: video-downloader
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CELERY_BROKER_URL
        value: redis://:password@hostname:6379/0
      - key: RESULT_BACKEND
        value: redis://:password@hostname:6379/0
